### ISSUE TITLE
hello world fails to build with 0.11.0-alpha4 on intel_s1000_crb 

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/sdk-ng#144]
`./scripts/sanitycheck -s samples/hello_world/sample.helloworld -p intel_s1000_crb`
Get the following error:

```
/home/galak/git/z-sdk-test/zephyr/soc/xtensa/intel_s1000/soc.c:8:10: fatal error: xtensa_api.h: No such file or directory
    8 | #include <xtensa_api.h>
      |          ^~~~~~~~~~~~~~

```

**Comment by dcpleung** [comment]
Seems to be caused by the 2d7460482de9ee1aaaa05a48ac9f5db2fb9114a3 (headers: Refactor kernel and arch headers).

**Comment by dcpleung** [comment]
Should be fixed with latest commit on https://github.com/zephyrproject-rtos/zephyr/pull/20221
